import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Nav from "@/component/nav/nav";
import Footer from "@/component/footer/footer";
import 'react-multi-carousel/lib/styles.css';
import Loading from "@/app/loading";
import {Suspense} from "react";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <body className={inter.className}>
              {children}
          </body>
    </html>
  )
}
