import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Nav from "@/component/nav/nav";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Nav style={{ position: 'absolute', top: 0, left: 0, right: 0, zIndex:9999, marginTop:'8px' }} />
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
